apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagtracker-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tagtracker-backend
  template:
    metadata:
      labels:
        app: tagtracker-backend
    spec:
      containers:
      - name: tagtracker-backend
        image: gcr.io/[PROJECT_ID]/tagtracker-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        - name: PORT
          value: "3000"
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              name: google-cloud-config
              key: project_id
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/var/secrets/google/credentials.json"
        volumeMounts:
        - name: google-cloud-credentials
          mountPath: "/var/secrets/google"
          readOnly: true
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      volumes:
      - name: google-cloud-credentials
        secret:
          secretName: google-cloud-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: tagtracker-backend
spec:
  selector:
    app: tagtracker-backend
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP 